apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-api
  labels:
    app: wine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wine-api
  template:
    metadata:
      labels:
        app: wine-api
    spec:
      containers:
        - name: wine-api
          image: jozu.ml/oyedeletemitope76/wine-quality-modelkit/basic:v1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
