apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: wine-api
 namespace: flux-system
spec:
 interval: 1m0s
 ref:
   branch: master
 url: https://github.com/”<<your github repo>>”/ml-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: wine-api
 namespace: flux-system
spec:
 interval: 1m0s
 path: ./apps/wine-api
 prune: true
 sourceRef:
   kind: GitRepository
   name: wine-api
 targetNamespace: default
 healthChecks:
   - apiVersion: apps/v1
     kind: Deployment
     name: wine-api
     namespace: default
