apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: wine-api
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: ml-api
