apiVersion: v1
kind: Service
metadata:
  name: wine-api-service
  labels:
    app: wine-api
spec:
  selector:
    app: wine-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
